version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - dependencies
    registries:
      - "company-github"
    allow:
      - dependency-type: "direct"
    groups:
      major-updates:
        patterns: ["*"]
        update-types: ["major"]
      minor-patch-updates:
        patterns: ["*"]
        update-types: ["minor", "patch"]
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
      timezone: "UTC"
    commit-message:
      prefix: "chore"
    labels:
      - dependencies
