version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - govet
    - importas
    - inamedparam
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - testpackage
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    errorlint:
      asserts: false
    funlen:
      lines: 100
      statements: 50
    gocyclo:
      min-complexity: 15
    govet:
      enable:
        - nilness
        - shadow
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 140
    misspell:
      locale: US
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
    revive:
      confidence: 0.8
      severity: warning
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        text: 'shadow: declaration of "err" shadows declaration at'
      - linters:
          - funlen
        path: _test\.go
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint