name: Go

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: stable
  
    - name: Setup
      run: |
        go install github.com/mattn/goveralls@latest

    - name: Test
      run: go test -v -covermode=count -coverprofile=coverage.out

    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}
        path-to-lcov: coverage.out